"""add password and email to users table

Revision ID: 17ba37ea26b
Revises: 265763040cc
Create Date: 2014-07-11 12:40:19.952617

"""

# revision identifiers, used by Alembic.
revision = '17ba37ea26b'
down_revision = '265763040cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=60), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
