"""users - default value for first and last name

Revision ID: 1e81edd50a2
Revises: 17ba37ea26b
Create Date: 2014-07-12 10:15:43.449962

"""

# revision identifiers, used by Alembic.
revision = '1e81edd50a2'
down_revision = '17ba37ea26b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    ### end Alembic commands ###
