"""users table fix password field

Revision ID: 3fb0f9f51f
Revises: d0eba3d032
Create Date: 2014-07-16 17:27:51.522120

"""

# revision identifiers, used by Alembic.
revision = '3fb0f9f51f'
down_revision = 'd0eba3d032'

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import PasswordType


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=PasswordType(max_length=1137),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=PasswordType(max_length=1137),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    ### end Alembic commands ###
